# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathew Hall
email: mathew.hall\x40sheffield.ac.uk
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mathew-hall.github.io" # the base hostname & protocol for your site
twitter_username: mathew_hall
github_username:  mathew-hall
bitbucket_username: mathew_hall

# Build settings
markdown: kramdown